# Generated by Django 3.1.1 on 2020-10-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roastboastmodel',
            name='total_vote',
            field=models.IntegerField(default=0),
        ),
    ]
