# Generated by Django 3.1.1 on 2020-10-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostapi', '0004_auto_20201001_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roastboastmodel',
            name='choices',
            field=models.CharField(choices=[('Boast', True), (False, 'Roast')], default=True, max_length=5),
        ),
    ]
